### PR TITLE
Add coleSaysHello

### PR DESCRIPTION
**Pull request by cole-maxwell1**
This adds the most amazing greeting one could ever read from the terminal!!! The alphabetical order of the greeters is also maintained.

### CODE REVIEW

**Review by NikFBail — COMMENTED** [review]
Looks like it should work

**Review by Shua59 — DISMISSED** [review]
Looks good

**Review by albright220 — APPROVED** [review]
Looks good to me

**Review by NikFBail — COMMENTED** [review]
Looks good

**Pull request merged**
