### PR TITLE
Add Zeke's Hello

### PR DESCRIPTION
**Pull request by krug0102**
This adds my greeting to Hellos.java

### CODE REVIEW

**Review by CBeane313 — COMMENTED** [review]
Looks good! The two additions were made!

**Review by cole-maxwell1 — COMMENTED** [review]
Nice!

**Review by NicMcPhee — DISMISSED** [review]
This looks swell - thanks.

**Review by OllieWillette667 — DISMISSED** [review]
Looks good

**Review by Kahnurd — DISMISSED** [review]
I suppose

**Review by caidongting0823 — DISMISSED** [review]
Looks Perfect!

**Review by NicMcPhee — DISMISSED** [review]

**Review by NicMcPhee — APPROVED** [review]

**Pull request merged**
