### PR TITLE
Added Max and Conner Hellos

### PR DESCRIPTION
**Pull request by Kahnurd**
we went into the hellos file and added Conner and Max's hellos.
Co-authored-by:  Max Quintavalle <quint218@umn.edu>

### CODE REVIEW

**Review by NikFBail — COMMENTED** [review]
Looks good

**Review by Shua59 — DISMISSED** [review]
Looks good - hello!

**Review by cole-maxwell1 — COMMENTED** [review]
Amazing!!!

**Review by krug0102 — COMMENTED** [review]
Nice job

**Review by quintmax — APPROVED** [review]
we good chief

**Pull request merged**
