### PR TITLE
Jan 20 | Added Dongting's Greeting

### PR DESCRIPTION
**Pull request by caidongting0823**
1. Added Dongting's Greeting

### CODE REVIEW

**Review by OllieWillette667 — DISMISSED** [review]
Looks good

**Review by NikFBail — COMMENTED** [review]
I think that builder.append(dongtingSaysHello()); should be below builder.append(conSaysHello()); for it to work. I could be wrong though

**Comment by caidongting0823** [comment]
> I think that builder.append(dongtingSaysHello()); should be below builder.append(conSaysHello()); for it to work. I could be wrong though

Thank you! i will check that out

**Review by YuboMao — COMMENTED** [review]
--

**Comment by YuboMao** [comment]
good job

**Review by YuboMao — COMMENTED** [review]
__

**Review by YuboMao — DISMISSED** [review]

**Review by NicMcPhee — DISMISSED** [review]
Looks great – merge away!

**Review by cole-maxwell1 — APPROVED** [review]
Look good Dongting!

**Pull request merged**
