### PR TITLE
Add John greeting

### PR DESCRIPTION
**Pull request by jpwalbran**
Added johnSaysHello() and called alphabetically in the generateOutput() method. Additionally, reordered the *saysHello() methods to reflect the call order in generateOutput().

### CODE REVIEW

**Review by NikFBail — COMMENTED** [review]
It looks good to me, should work.

**Review by krug0102 — COMMENTED** [review]
Looks good

**Review by albright220 — DISMISSED** [review]
Looks good to me

**Review by albright220 — APPROVED** [review]
Looks good to me

**Pull request merged**
