### PR TITLE
Add Josh Hello

### PR DESCRIPTION
**Pull request by Shua59**
This adds a new hello from Josh that reads: "Josh says 'Hello!'\n"

### CODE REVIEW

**Review by NikFBail — COMMENTED** [review]
Noice, looks good

**Review by NicMcPhee — DISMISSED** [review]
That looks great - thanks!

**Review by NikFBail — COMMENTED** [review]
2 thumbs up

**Review by Kahnurd — DISMISSED** [review]
Not sure whats going on here, but I'll allow it

**Review by CBeane313 — DISMISSED** [review]
NICE

**Review by NikFBail — DISMISSED** [review]
I think this should work

**Review by caidongting0823 — DISMISSED** [review]
Looks Wonderful!

**Review by NicMcPhee — DISMISSED** [review]

**Review by caidongting0823 — APPROVED** [review]
Looks great! : )

**Pull request merged**
